package com.neuralcoder.utilities;

import java.util.logging.Logger;

public final class GlobalProperties {

	public static final String PLUGIN_NAME = "KMetrics";

	public static final String MISRA_LINK = "Misra Details";

	public static final String PLUGIN_ICON = "/plugin/MetricsPlugin/misra.png";
	
	public static final String PLUGIN_ICON_K = "/plugin/MetricsPlugin/k2.png";
	public static final String PLUGIN_ICON_K1 = "/plugin/KMetrics/k.png";
	public static final String K_LINK_NAME = "Quality KPIs";
	public static final String K1_LINK_NAME = "Quality KPI - K1/K1 lite";

	public static final String PLUGIN_URL = "metrics";
	public static final String PLUGIN_URL_K = "Kmetrics";
	public static final String PLUGIN_URL_K1 = "KAmetrics";


	public static final String XML_PARSING_PATHS_PROPERTIES = "META-INF/xml_paths.properties";

	public static final String PROJECT_METRICS_XML_FILE = "projectMetrics.xml";
	
	public static  String SW_DASHBOARD_FILE= "";
	public static  String SW_JUNIT_FILE="";
	public static  String FILE_PROPERTIES="";
	
	
	public static String SWPath="";
	public static String JUPath="";
	public static String FPPath="";
	
	public static final String METRICS_FOLDER = "metrics";
	public static final String K_FOLDER = "Kreport";

	// in KPI folder is copied the last build K1/ K1lite value/s.
	public static final String KPI_FOLDER = "KPI";
	
	public static final Logger logger = Logger.getLogger(GlobalProperties.class.getName());

	/*
	 * Keys and mesages
	 */

	// ROM 
	public static final String _KEY_AVAILABLE_ROM = "available_rom";
	public static final String _KEY_USED_ROM = "used_rom";
	public static final String _KEY_MEMORY_OBJECT_ROM = "memory_object_rom";
	//EEPROM
	public static final String _KEY_AVAILABLE_EEPROM = "available_eeprom";
	public static final String _KEY_USED_EEPROM = "used_eeprom";
	public static final String _KEY_MEMORY_OBJECT_EEPROM = "memory_object_eeprom";
	//RAM
	public static final String _KEY_AVAILABLE_RAM = "available_ram";
	public static final String _KEY_USED_RAM = "used_ram";
	public static final String _KEY_MEMORY_OBJECT_RAM = "memory_object_ram";

	public static final double _1024 = 1024.0;

	public static final String _KEY_CYCLO_BETWEEN_15_AND_30 = "functionsCyclo15To30";
	public static final String _KEY_CYCLO_MORE_THAN_30 = "functionsCycloMore30";

	public static final String _KEY_ELOCSAFETY = "elocsafetycode";
	//Used for K2
	public static final String _KEY_ELOCSAFETY_TOTAL = "eloctotal";

	public static final String _KEY_ELOCNONSAFETY = "elocnonsafetycode";

	public static final String _KEY_BUILD_WARNINGS = "build_warnings";
	public static final String _KEY_LINKER_WARNINGS = "linker_warnings";
	
	//Used for K2
	public static final String _KEY_DEVIATIONS_SAFETY_ABSOLUTE_TOTAL = "deviations_safety_absolute_total";
	
	public static final String _KEY_DEVIATIONS_SAFETY_ABSOLUTE_SUBCONTRACTED = "deviations_safety_absolute_subcontracted";
	public static final String _KEY_DEVIATIONS_SAFETY_ABSOLUTE_3RDPARTY = "deviations_safety_absolute_3rdparty";
	public static final String _KEY_DEVIATIONS_SAFETY_ABSOLUTE_AUTOGENERATED = "deviations_safety_absolute_autogenerated";
	public static final String _KEY_DEVIATIONS_SAFETY_ABSOLUTE_UNMODIFIEDREUSED = "deviations_safety_absolute_unmodifiedreused";
	public static final String _KEY_DEVIATIONS_SAFETY_ABSOLUTE_MODIFIEDREUSED = "deviations_safety_absolute_modifiedreused";
	public static final String _KEY_DEVIATIONS_SAFETY_ABSOLUTE_NEWCODE = "deviations_safety_absolute_newcode";

	public static final String _KEY_DEVIATIONS_NONSAFETY_ABSOLUTE_SUBCONTRACTED = "deviations_nonsafety_absolute_subcontracted";
	public static final String _KEY_DEVIATIONS_NONSAFETY_ABSOLUTE_3RDPARTY = "deviations_nonsafety_absolute_3rdparty";
	public static final String _KEY_DEVIATIONS_NONSAFETY_ABSOLUTE_AUTOGENERATED = "deviations_nonsafety_absolute_autogenerated";
	public static final String _KEY_DEVIATIONS_NONSAFETY_ABSOLUTE_UNMODIFIEDREUSED = "deviations_nonsafety_absolute_unmodifiedreused";
	public static final String _KEY_DEVIATIONS_NONSAFETY_ABSOLUTE_MODIFIEDREUSED = "deviations_nonsafety_absolute_modifiedreused";
	public static final String _KEY_DEVIATIONS_NONSAFETY_ABSOLUTE_NEWCODE = "deviations_nonsafety_absolute_newcode";

	public static final String _KEY_DEVIATIONS_SAFETY_100ELOC_SUBCONTRACTED = "deviations_safety_per100ELOC_subcontracted";
	public static final String _KEY_DEVIATIONS_SAFETY_100ELOC_3RDPARTY = "deviations_safety_per100ELOC_3rdparty";
	public static final String _KEY_DEVIATIONS_SAFETY_100ELOC_AUTOGENERATED = "deviations_safety_per100ELOC_autogenerated";
	public static final String _KEY_DEVIATIONS_SAFETY_100ELOC_UNMODIFIEDREUSED = "deviations_safety_per100ELOC_unmodifiedreused";
	public static final String _KEY_DEVIATIONS_SAFETY_100ELOC_MODIFIEDREUSED = "deviations_safety_per100ELOC_modifiedreused";
	public static final String _KEY_DEVIATIONS_SAFETY_100ELOC_NEWCODE = "deviations_safety_per100ELOC_newcode";

	public static final String _KEY_DEVIATIONS_NONSAFETY_100ELOC_SUBCONTRACTED = "deviations_nonsafety_per100ELOC_subcontracted";
	public static final String _KEY_DEVIATIONS_NONSAFETY_100ELOC_3RDPARTY = "deviations_nonsafety_per100ELOC_3rdparty";
	public static final String _KEY_DEVIATIONS_NONSAFETY_100ELOC_AUTOGENERATED = "deviations_nonsafety_per100ELOC_autogenerated";
	public static final String _KEY_DEVIATIONS_NONSAFETY_100ELOC_UNMODIFIEDREUSED = "deviations_nonsafety_per100ELOC_unmodifiedreused";
	public static final String _KEY_DEVIATIONS_NONSAFETY_100ELOC_MODIFIEDREUSED = "deviations_nonsafety_per100ELOC_modifiedreused";
	public static final String _KEY_DEVIATIONS_NONSAFETY_100ELOC_NEWCODE = "deviations_nonsafety_per100ELOC_newcode";

	public static final String _KEY_MISRA_SAFETY_REQUIRED_SUBCONTRACTED = "misra_safety_required_subcontracted";
	public static final String _KEY_MISRA_SAFETY_REQUIRED_3RDPARTY = "misra_safety_required_3rdparty";
	public static final String _KEY_MISRA_SAFETY_REQUIRED_AUTOGENERATED = "misra_safety_required_autogenerated";
	public static final String _KEY_MISRA_SAFETY_REQUIRED_UNMODIFIEDREUSED = "misra_safety_required_unmodifiedreused";
	public static final String _KEY_MISRA_SAFETY_REQUIRED_MODIFIEDREUSED = "misra_safety_required_modifiedreused";
	public static final String _KEY_MISRA_SAFETY_REQUIRED_NEWCODE = "misra_safety_required_newcode";

	public static final String _KEY_MISRA_SAFETY_OBLIGATORY_SUBCONTRACTED = "misra_safety_obligatory_subcontracted";
	public static final String _KEY_MISRA_SAFETY_OBLIGATORY_3RDPARTY = "misra_safety_obligatory_3rdparty";
	public static final String _KEY_MISRA_SAFETY_OBLIGATORY_AUTOGENERATED = "misra_safety_obligatory_autogenerated";
	public static final String _KEY_MISRA_SAFETY_OBLIGATORY_UNMODIFIEDREUSED = "misra_safety_obligatory_unmodifiedreused";
	public static final String _KEY_MISRA_SAFETY_OBLIGATORY_MODIFIEDREUSED = "misra_safety_obligatory_modifiedreused";
	public static final String _KEY_MISRA_SAFETY_OBLIGATORY_NEWCODE = "misra_safety_obligatory_newcode";

	public static final String _KEY_MISRA_NONSAFETY_REQUIRED_SUBCONTRACTED = "misra_nonsafety_required_subcontracted";
	public static final String _KEY_MISRA_NONSAFETY_REQUIRED_3RDPARTY = "misra_nonsafety_required_3rdparty";
	public static final String _KEY_MISRA_NONSAFETY_REQUIRED_AUTOGENERATED = "misra_nonsafety_required_autogenerated";
	public static final String _KEY_MISRA_NONSAFETY_REQUIRED_UNMODIFIEDREUSED = "misra_nonsafety_required_unmodifiedreused";
	public static final String _KEY_MISRA_NONSAFETY_REQUIRED_MODIFIEDREUSED = "misra_nonsafety_required_modifiedreused";
	public static final String _KEY_MISRA_NONSAFETY_REQUIRED_NEWCODE = "misra_nonsafety_required_newcode";

	public static final String _KEY_MISRA_NONSAFETY_OBLIGATORY_SUBCONTRACTED = "misra_nonsafety_obligatory_subcontracted";
	public static final String _KEY_MISRA_NONSAFETY_OBLIGATORY_3RDPARTY = "misra_nonsafety_obligatory_3rdparty";
	public static final String _KEY_MISRA_NONSAFETY_OBLIGATORY_AUTOGENERATED = "misra_nonsafety_obligatory_autogenerated";
	public static final String _KEY_MISRA_NONSAFETY_OBLIGATORY_UNMODIFIEDREUSED = "misra_nonsafety_obligatory_unmodifiedreused";
	public static final String _KEY_MISRA_NONSAFETY_OBLIGATORY_MODIFIEDREUSED = "misra_nonsafety_obligatory_modifiedreused";
	public static final String _KEY_MISRA_NONSAFETY_OBLIGATORY_NEWCODE = "misra_nonsafety_obligatory_newcode";

	public static final String _KEY_MISRA_SAFETY_ADVISORY_SUBCONTRACTED = "misra_safety_advisory_subcontracted";
	public static final String _KEY_MISRA_SAFETY_ADVISORY_3RDPARTY = "misra_safety_advisory_3rdparty";
	public static final String _KEY_MISRA_SAFETY_ADVISORY_AUTOGENERATED = "misra_safety_advisory_autogenerated";
	public static final String _KEY_MISRA_SAFETY_ADVISORY_UNMODIFIEDREUSED = "misra_safety_advisory_unmodifiedreused";
	public static final String _KEY_MISRA_SAFETY_ADVISORY_MODIFIEDREUSED = "misra_safety_advisory_modifiedreused";
	public static final String _KEY_MISRA_SAFETY_ADVISORY_NEWCODE = "misra_safety_advisory_newcode";

	public static final String _KEY_MISRA_SAFETY_RECOMMENDED_SUBCONTRACTED = "misra_safety_recommended_subcontracted";
	public static final String _KEY_MISRA_SAFETY_RECOMMENDED_3RDPARTY = "misra_safety_recommended_3rdparty";
	public static final String _KEY_MISRA_SAFETY_RECOMMENDED_AUTOGENERATED = "misra_safety_recommended_autogenerated";
	public static final String _KEY_MISRA_SAFETY_RECOMMENDED_UNMODIFIEDREUSED = "misra_safety_recommended_unmodifiedreused";
	public static final String _KEY_MISRA_SAFETY_RECOMMENDED_MODIFIEDREUSED = "misra_safety_recommended_modifiedreused";
	public static final String _KEY_MISRA_SAFETY_RECOMMENDED_NEWCODE = "misra_safety_recommended_newcode";

	public static final String _KEY_MISRA_NONSAFETY_ADVISORY_SUBCONTRACTED = "misra_nonsafety_advisory_subcontracted";
	public static final String _KEY_MISRA_NONSAFETY_ADVISORY_3RDPARTY = "misra_nonsafety_advisory_3rdparty";
	public static final String _KEY_MISRA_NONSAFETY_ADVISORY_AUTOGENERATED = "misra_nonsafety_advisory_autogenerated";
	public static final String _KEY_MISRA_NONSAFETY_ADVISORY_UNMODIFIEDREUSED = "misra_nonsafety_advisory_unmodifiedreused";
	public static final String _KEY_MISRA_NONSAFETY_ADVISORY_MODIFIEDREUSED = "misra_nonsafety_advisory_modifiedreused";
	public static final String _KEY_MISRA_NONSAFETY_ADVISORY_NEWCODE = "misra_nonsafety_advisory_newcode";

	public static final String _KEY_MISRA_NONSAFETY_RECOMMENDED_SUBCONTRACTED = "misra_nonsafety_recommended_subcontracted";
	public static final String _KEY_MISRA_NONSAFETY_RECOMMENDED_3RDPARTY = "misra_nonsafety_recommended_3rdparty";
	public static final String _KEY_MISRA_NONSAFETY_RECOMMENDED_AUTOGENERATED = "misra_nonsafety_recommended_autogenerated";
	public static final String _KEY_MISRA_NONSAFETY_RECOMMENDED_UNMODIFIEDREUSED = "misra_nonsafety_recommended_unmodifiedreused";
	public static final String _KEY_MISRA_NONSAFETY_RECOMMENDED_MODIFIEDREUSED = "misra_nonsafety_recommended_modifiedreused";
	public static final String _KEY_MISRA_NONSAFETY_RECOMMENDED_NEWCODE = "misra_nonsafety_recommended_newcode";

}
